### ISSUE TITLE
A type in the program ddeabm_example

### ISSUE THREAD

**Issue by kookma** [jacobwilliams/ddeabm#10]
In the example in the first page: https://github.com/jacobwilliams/ddeabm (program ddeabm_example)

`use kind_module`

should be replaced  with

`use ddeabm_kinds`

**Comment by kookma** [comment]
Also see this
```
call s%integrate(t,x,tf,idid=idid)
write(*,'(A/,*(F15.6/))') 'Final time:',t
write(*,'(A/,*(F15.6/))') 'Initial time:',x
```

Should be:

` write(*,'(A/,*(F15.6/))') 'Final state:',x`

**Comment by jacobwilliams** [comment]
Thanks! Fixed.
