### ISSUE TITLE
Order of accuracy

### ISSUE THREAD

**Issue by szaghi** [jacobwilliams/ddeabm#4]
@jacobwilliams 

Dear Jacob,

for cross-verification aims, I am using your ddeabm library, it is very nice.

I have tried to find some references, but I did not found details of the actual *Adamas-Bashforth-Moulton* scheme implemented. Is it a classical predictor-corrector scheme? How are done (if any) the implicit iterations? Which is the formal order of accuracy? Are the relative and absolute tolerances used for the corrector iterations? 

The above questions can be answered by a deep analysis of your code, but now I have not the time, so I tried the quick way, but feel free to ignore my bothering.

The questions arise from a very simple test, the pure linear advection PDE

``` du/dt = a * du/dx```

where `a` is a constant coefficient, in my test I had set `a=1`. For my test I am using the following code

```fortran
program ddeabm_example

use ddeabm_module
use kind_module

implicit none

integer, parameter     :: n = 100
type(ddeabm_class)     :: s
real(wp), dimension(n) :: u0, u
real(wp)               :: t0, tf, t
integer                :: idid

call s%initialize(n, maxnum=10000, df=advection, rtol=[1.0e-6_wp], atol=[1.0e-6_wp])

call set_square_wave_initial_state(u=u0)

t0 = 0.0_wp ! initial time (sec)
tf = 8.0_wp ! final time (sec)

write(*,'(A/,*(F15.6/))') 'Initial time:',t0
write(*,'(A/,*(F15.6/))') 'Initial state:',u0
t = t0
u = u0
call s%integrate(t, u, tf, idid=idid)
write(*,'(A/,*(F15.6/))') 'Final time:',t
write(*,'(A/,*(F15.6/))') 'Initial time:',u

contains
   subroutine advection(me, t, x, xdot)
   class(ddeabm_class), intent(inout) :: me
   real(wp),            intent(in)    :: t
   real(wp),            intent(in)    :: x(:)
   real(wp),            intent(out)   :: xdot(:)
   real(wp)                           :: u(0:size(x, dim=1)+1)
   real(wp)                           :: f(0:size(x, dim=1))
   real(wp)                           :: Dx
   integer                            :: Ni
   integer                            :: i

   Ni = size(x, dim=1)
   Dx = 1._wp / Ni
   u(1:Ni) = x
   u(0) = u(Ni)
   u(Ni+1) = u(1)
   do i=0, Ni
      f(i) = u(i)
   enddo
   do i=1, Ni
       xdot(i) = (f(i - 1) - f(i)) / Dx
   enddo
   endsubroutine advection

   subroutine set_square_wave_initial_state(u)
   real(wp), intent(inout) :: u(1:)
   real(wp)                :: x(1:size(u, dim=1))
   real(wp)                :: Dx
   integer                 :: i

   Dx = 1._wp / size(u, dim=1)
   do i=1, size(u, dim=1)
      x(i) = Dx * i - 0.5_wp * Dx
      if     (x(i) < 0.25_wp) then
         u(i) = 0._wp
      elseif (0.25_wp <= x(i) .and. x(i) < 0.75_wp) then
         u(i) = 1._wp
      else
         u(i) = 0._wp
      endif
   enddo
   endsubroutine set_square_wave_initial_state
end program ddeabm_example
```

As you can see, the spatial operator is a first order upwind scheme to advect (integrate) a square wave for 8 periods (boundary conditions are periodic), thus I expect first order global accuracy. However, I obtained a very dissipative solution, e.g. 

![square_wave_advection](https://cloud.githubusercontent.com/assets/1661942/26065557/a7428b6a-3994-11e7-9aad-1eff8642d976.png)

The dissipation of the square wave (that should be simple advected, there is no diffusion other than the numerical one) is too much if compared with the Euler explicit integration (with FOODIE), e.g.
![square_wave_advection_euler](https://cloud.githubusercontent.com/assets/1661942/26065742/2a8f296a-3995-11e7-8c47-d26a957ce080.png)

I suspect that in ddeabm the error tolerances are used to *stabilize* high order Adams-Bashforth-Moulton scheme as I can do with high order AB using very low CFL. Thus my curiosity to know some details of the ddeabm scheme.

Cheers

**Comment by jacobwilliams** [comment]
I don't know the answer to your questions offhand. The code says that it uses:
```
a modified divided difference form of the adams pece formulas.  local
extrapolation is used to improve absolute stability and accuracy.
the code adjusts its order and step size to control the local error
per unit step in a generalized sense.  special devices are included
to control roundoff error and to detect when the user is requesting
too much accuracy.
```
The theory is described in the 1975 book I reference in the Readme. I do have it somewhere, I can try to find it and see if it has more information.

**Comment by szaghi** [comment]
@jacobwilliams 

Dear Jacob, this is enough, I will try to find the book. I am curious to learn how the roundoff is handled. I suspected the order/step size is adjusted by means of tolerances thus the excessive dissipation I observed: maybe if I increase the tolerances the dissipation disappears...

As always thank you very much!

Cheers
