### ISSUE TITLE
N-Dimensional events

### ISSUE THREAD

**Issue by mtozimek** [jacobwilliams/ddeabm#6]
Hello Jacob, this is a great modern implementation of DDEABM!  I was wondering if the code is capable of handling a vector of events rather than a scalar event?  I perused the event_func syntax (starting on line 201 of ddeabm_module.f90), and noticed that it looks like event function "g" is defined as a scalar real(wp), intent(out).  Is it possible to have g run as a dynamic array of events, and stop on any of them that happen to hit zero?

For context, I have a working example in the n-body problem that *might* pass through multiple spheres of influence.  My goal would be to report the SOI that I stop on (if any).  I think there are hacks to do this with a scalar, but ideally one would want to do it with a vector of stopping events.  Apologies if this is already possible as-is, I just couldn't tell upon reading the documentation.

**Comment by jacobwilliams** [comment]
Vector events aren't currently in there. But, I agree, that would be great to have! I don't think it would be hard to add...but I'd need to think about it. I guess it will also need to report which even was triggered? I can add it... but no guarantee as to when that would be.

**Comment by mtozimek** [comment]
Thanks for the response!  I would be happy to use the feature if it does ever happen to be added.

**Comment by jacobwilliams** [comment]
@mtozimek I think I've got it working on the latest `master`. It's basically just a copy/paste/modification of the scalar code. The new class to use for ND event functions is `ddeabm_with_event_class_vec`. If you use it, I'd be interested to hear if it works, or if you have any other suggestions.
